name: T&P Notifier

on:
  schedule:
    # Runs the job every 5 hrs
    - cron: '0 */5 * * *'
  # Allows for manual runs from the GitHub Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install npm dependencies
        run: npm install

      - name: Run initialization script once
        run: npm run init
        if: github.event_name == 'workflow_dispatch'

      - name: Run monitoring script
        run: npm start
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          LOGIN_PAGE_URL: ${{ secrets.LOGIN_PAGE_URL }}
          TARGET_PAGE_URL: ${{ secrets.TARGET_PAGE_URL }}
          CHECK_INTERVAL_MINUTES: ${{ secrets.CHECK_INTERVAL_MINUTES }}
          EMAIL_SERVICE: ${{ secrets.EMAIL_SERVICE }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          RECIPIENT_EMAILS: ${{ secrets.RECIPIENT_EMAILS }}
          MONGO_URI: ${{ secrets.MONGO_URI }}