name: T&P Notifier

on:
  schedule:
    # Runs the job every 10 minutes
    - cron: '*/10 * * * *'
  # Allows for manual runs from the GitHub Actions tab
  workflow_dispatch:

# Add permissions to allow the workflow to write to the repository
permissions:
  contents: write

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # Add a token to enable the checkout to have push permissions
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install npm dependencies
        run: npm install

      - name: Run initialization script once
        run: npm run init
        if: github.event_name == 'workflow_dispatch'

      - name: Run monitoring script
        run: npm start
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          LOGIN_PAGE_URL: ${{ secrets.LOGIN_PAGE_URL }}
          TARGET_PAGE_URL: ${{ secrets.TARGET_PAGE_URL }}
          CHECK_INTERVAL_MINUTES: ${{ secrets.CHECK_INTERVAL_MINUTES }}
          EMAIL_SERVICE: ${{ secrets.EMAIL_SERVICE }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          RECIPIENT_EMAILS: ${{ secrets.RECIPIENT_EMAILS }}

      # Corrected Step: Commit and push changes back to the repository
      - name: Commit updated data files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/
          git commit -m "Update data files with latest scrape results" || exit 0
          git push